### PR TITLE
Update/shortcodes ultimate

### PR DESCRIPTION
**Pull request by neophytosconst**

### CODE REVIEW

**Comment by neophytosconst** [comment]
Now all current shortcodes have also been registered to plugin 'Shortcodes Ultimate' (only if plugin is activated) and users can use our custom shortcodes using the plugins interface (Using the plugins GUI interface with a form to fill up the parameters).

Can we get a release for this to add this in project template

**Comment by mamchenkov** [comment]
@neophytosconst since you are already doing some file reorganization in this PR, can you please move all PHP files into a lib/ folder or something.  So that the root folder of the plugin just has a single PHP file, and README + LICENSE.

Ideally, all those functions can also be organized into a class (static methods?) to minimize the function name pollution.  But this can be done at a later stage, of course.

**Comment by neophytosconst** [comment]
@mamchenkov yes I had that in mind but did not want to spend any more time for this.
I will do this quickly today.

Just done the sorting thing

**Comment by mamchenkov** [comment]
:+1:

**Comment by mamchenkov** [comment]
@neophytosconst Excellent work! Thanks! :+1:

**Pull request merged**
